//___FILEHEADER___

import Foundation
import MVVMRB

protocol ___VARIABLE_productName:identifier___RouterDependencyProtocol {
}

protocol ___VARIABLE_productName:identifier___RouterProtocol {
}

class ___VARIABLE_productName:identifier___Router: Router<___VARIABLE_productName:identifier___RouterDependencyProtocol, ___VARIABLE_productName:identifier___ViewModelProtocol>, ___VARIABLE_productName:identifier___RouterProtocol {
}
